### ISSUE TITLE
Travis failure test_ta_17_heal_fully_success

### ISSUE THREAD

**Issue by akkowal2** [DBN16CO/Tactics#140]
https://travis-ci.org/DBN16CO/Tactics/builds/204442201
```
======================================================================
FAIL: test_ta_17_heal_fully_success (Game.tests.TestTakeAction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/DBN16CO/Tactics/Server/Game/tests.py", line 1311, in test_ta_17_heal_fully_success
    result, unit, tgt, heal_data = self.helper_execute_heal_success(self.heal_cmd)
  File "/home/travis/build/DBN16CO/Tactics/Server/Game/tests.py", line 758, in helper_execute_heal_success
    result = self.helper_execute_move_success(command)
  File "/home/travis/build/DBN16CO/Tactics/Server/Game/tests.py", line 706, in helper_execute_move_success
    result = self.helper_execute_success(command)
  File "/home/travis/build/DBN16CO/Tactics/Server/Communication/testhelper.py", line 211, in helper_execute_success
    self.assertTrue(result["Success"])
AssertionError: False is not true
```

**Comment by DaBernMon** [comment]
Log for the test:
[02/22/17 09:05:20 PM testhelper:167] DEBUG ============  Starting Test: test_ta_17_heal_fully_success ============
[02/22/17 09:05:20 PM create_dat: 34]  INFO Creating Version object...
[02/22/17 09:05:20 PM create_dat: 40]  INFO Creating Ability objects...
[02/22/17 09:05:20 PM create_dat: 46]  INFO Creating Action objects...
[02/22/17 09:05:20 PM create_dat: 52]  INFO Creating Leader objects...
[02/22/17 09:05:20 PM create_dat: 62]  INFO Creating Perk objects...
[02/22/17 09:05:20 PM create_dat: 69]  INFO Creating Map objects...
[02/22/17 09:05:20 PM create_dat: 75]  INFO Creating Stat objects...
[02/22/17 09:05:20 PM create_dat: 81]  INFO Creating Terrain objects...
[02/22/17 09:05:20 PM create_dat: 88]  INFO Creating Class objects...
[02/22/17 09:05:20 PM maphelper.:114] DEBUG Movement Dictionary:
[02/22/17 09:05:20 PM maphelper.:115] DEBUG {u'R': {u'Cleric': 1, u'Flier': 1, u'Archer': 1, u'Armor': 1, u'Swordsman': 1, u'Rogue': 1, u'Horseman': 1, u'Mage': 1}, u'M': {u'Cleric': 3, u'Flier': 1, u'Archer': 4, u'Armor': 99, u'Swordsman': 4, u'Rogue': 2, u'Horseman': 99, u'Mage': 3}, u'G': {u'Cleric': 1, u'Flier': 1, u'Archer': 1, u'Armor': 1, u'Swordsman': 1, u'Rogue': 1, u'Horseman': 1, u'Mage': 1}, u'W': {u'Cleric': 99, u'Flier': 1, u'Archer': 99, u'Armor': 99, u'Swordsman': 99, u'Rogue': 99, u'Horseman': 99, u'Mage': 99}, u'F': {u'Cleric': 2, u'Flier': 1, u'Archer': 2, u'Armor': 3, u'Swordsman': 3, u'Rogue': 1, u'Horseman': 3, u'Mage': 2}}
[02/22/17 09:05:20 PM testhelper:100] DEBUG {"username": "game_user_1", "Command": "CU", "pw": "aaaaaaa", "email": "userOne@email.com"}
[02/22/17 09:05:20 PM testhelper: 62] DEBUG Chn.name=Test
[02/22/17 09:05:20 PM  router.py: 89] DEBUG Parsing incoming json request: 
{"username": "game_user_1", "Command": "CU", "pw": "aaaaaaa", "email": "userOne@email.com"}
[02/22/17 09:05:20 PM  router.py:117] DEBUG Received command: CU
[02/22/17 09:05:20 PM testhelper:103] DEBUG {"Token": "99e7a0cba95241c296c9453dd3213ee1", "Success": true}
[02/22/17 09:05:20 PM testhelper: 62] DEBUG Chn.name=Test
[02/22/17 09:05:20 PM  router.py: 89] DEBUG Parsing incoming json request: 
{"username": "game_user_1", "Command": "LGN", "pw": "aaaaaaa"}
[02/22/17 09:05:20 PM  router.py:117] DEBUG Received command: LGN
[02/22/17 09:05:21 PM testhelper: 62] DEBUG Chn.name=Test
[02/22/17 09:05:21 PM  router.py: 89] DEBUG Parsing incoming json request: 
{"Units": ["Flier", "Armor", "Rogue", "Horseman", "Mage", "Swordsman", "Cleric", "Archer"], "Perks": [], "Command": "ST", "Ability": "Extra Range", "Leader": "Sniper"}
[02/22/17 09:05:21 PM  router.py:117] DEBUG Received command: ST
[02/22/17 09:05:21 PM routeunith: 50] DEBUG {u'Ability': u'Extra Range', 'session_username': u'game_user_1', u'Perks': [], u'Command': u'ST', u'Units': [u'Flier', u'Armor', u'Rogue', u'Horseman', u'Mage', u'Swordsman', u'Cleric', u'Archer'], u'Leader': u'Sniper'}
[02/22/17 09:05:21 PM statichelp: 72] DEBUG Loading Version data...
[02/22/17 09:05:21 PM statichelp: 74] DEBUG Using latest version: 1.0
[02/22/17 09:05:21 PM statichelp: 77] DEBUG Loading Ability data...
[02/22/17 09:05:21 PM statichelp:162] DEBUG There are 4 objects in ability for version 1.0.
[02/22/17 09:05:21 PM statichelp: 83] DEBUG Loading Action data...
[02/22/17 09:05:21 PM statichelp:189] DEBUG There are 3 objects in action for version 1.0.
[02/22/17 09:05:21 PM statichelp: 89] DEBUG Loading Class data...
[02/22/17 09:05:21 PM statichelp:225] DEBUG There are 8 objects in class for version 1.0.
[02/22/17 09:05:21 PM statichelp:248] DEBUG There are 9 objects in Unit_Stat for class Flier version 1.0.
[02/22/17 09:05:21 PM statichelp:255] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Flier version 1.0.
[02/22/17 09:05:21 PM statichelp:248] DEBUG There are 9 objects in Unit_Stat for class Armor version 1.0.
[02/22/17 09:05:21 PM statichelp:255] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Armor version 1.0.
[02/22/17 09:05:21 PM statichelp:248] DEBUG There are 9 objects in Unit_Stat for class Rogue version 1.0.
[02/22/17 09:05:21 PM statichelp:255] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Rogue version 1.0.
[02/22/17 09:05:21 PM statichelp:248] DEBUG There are 9 objects in Unit_Stat for class Horseman version 1.0.
[02/22/17 09:05:21 PM statichelp:255] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Horseman version 1.0.
[02/22/17 09:05:21 PM statichelp:248] DEBUG There are 9 objects in Unit_Stat for class Mage version 1.0.
[02/22/17 09:05:21 PM statichelp:255] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Mage version 1.0.
[02/22/17 09:05:21 PM statichelp:248] DEBUG There are 9 objects in Unit_Stat for class Swordsman version 1.0.
[02/22/17 09:05:21 PM statichelp:255] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Swordsman version 1.0.
[02/22/17 09:05:21 PM statichelp:248] DEBUG There are 9 objects in Unit_Stat for class Cleric version 1.0.
[02/22/17 09:05:21 PM statichelp:255] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Cleric version 1.0.
[02/22/17 09:05:21 PM statichelp:248] DEBUG There are 9 objects in Unit_Stat for class Archer version 1.0.
[02/22/17 09:05:21 PM statichelp:255] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Archer version 1.0.
[02/22/17 09:05:21 PM statichelp: 95] DEBUG Loading Leader data...
[02/22/17 09:05:21 PM statichelp:283] DEBUG There are 5 objects in leader for version 1.0.
[02/22/17 09:05:21 PM statichelp:101] DEBUG Loading Map data...
[02/22/17 09:05:21 PM statichelp:320] DEBUG There are 2 objects in map for version 1.0.
[02/22/17 09:05:21 PM statichelp:107] DEBUG Loading Perk data...
[02/22/17 09:05:21 PM statichelp:366] DEBUG There are 4 objects in perk for version 1.0.
[02/22/17 09:05:21 PM statichelp:113] DEBUG Loading Stat data...
[02/22/17 09:05:21 PM statichelp:399] DEBUG There are 9 objects in stat for version 1.0.
[02/22/17 09:05:21 PM statichelp:119] DEBUG Loading Terrain data...
[02/22/17 09:05:21 PM statichelp:434] DEBUG There are 5 objects in terrain for version 1.0.
[02/22/17 09:05:21 PM testhelper: 62] DEBUG Chn.name=Test
[02/22/17 09:05:21 PM  router.py: 89] DEBUG Parsing incoming json request: 
{"Command": "FM"}
[02/22/17 09:05:21 PM  router.py:117] DEBUG Received command: FM
[02/22/17 09:05:21 PM  router.py:156] DEBUG Adding channel name to JSON: Test
[02/22/17 09:05:21 PM testhelper:100] DEBUG {"username": "game_user_2", "Command": "CU", "pw": "aaaaaaa", "email": "userTwo@email.com"}
[02/22/17 09:05:21 PM testhelper: 62] DEBUG Chn.name=Test2
[02/22/17 09:05:21 PM  router.py: 89] DEBUG Parsing incoming json request: 
{"username": "game_user_2", "Command": "CU", "pw": "aaaaaaa", "email": "userTwo@email.com"}
[02/22/17 09:05:21 PM  router.py:117] DEBUG Received command: CU
[02/22/17 09:05:21 PM testhelper:103] DEBUG {"Token": "ad567cec122242c6ba02e0fb9b12bd8d", "Success": true}
[02/22/17 09:05:21 PM testhelper: 62] DEBUG Chn.name=Test2
[02/22/17 09:05:21 PM  router.py: 89] DEBUG Parsing incoming json request: 
{"username": "game_user_2", "Command": "LGN", "pw": "aaaaaaa"}
[02/22/17 09:05:21 PM  router.py:117] DEBUG Received command: LGN
[02/22/17 09:05:22 PM testhelper: 62] DEBUG Chn.name=Test2
[02/22/17 09:05:22 PM  router.py: 89] DEBUG Parsing incoming json request: 
{"Units": ["Flier", "Armor", "Rogue", "Horseman", "Mage", "Swordsman", "Cleric", "Archer"], "Perks": [], "Command": "ST", "Ability": "Extra Range", "Leader": "Sniper"}
[02/22/17 09:05:22 PM  router.py:117] DEBUG Received command: ST
[02/22/17 09:05:22 PM routeunith: 50] DEBUG {u'Ability': u'Extra Range', 'session_username': u'game_user_2', u'Perks': [], u'Command': u'ST', u'Units': [u'Flier', u'Armor', u'Rogue', u'Horseman', u'Mage', u'Swordsman', u'Cleric', u'Archer'], u'Leader': u'Sniper'}
[02/22/17 09:05:22 PM testhelper: 62] DEBUG Chn.name=Test2
[02/22/17 09:05:22 PM  router.py: 89] DEBUG Parsing incoming json request: 
{"Command": "FM"}
[02/22/17 09:05:22 PM  router.py:117] DEBUG Received command: FM
[02/22/17 09:05:22 PM  router.py:156] DEBUG Adding channel name to JSON: Test2
[02/22/17 09:05:22 PM   tasks.py: 48] DEBUG Processing matchmaking queue
[02/22/17 09:05:22 PM   tasks.py: 68]  INFO Found a match: game_user_1 vs. game_user_2
[02/22/17 09:05:22 PM   tasks.py: 80]  INFO Users have played each other 0 times.
[02/22/17 09:05:22 PM   tasks.py: 86]  INFO game_user_1 will take the first turn
[02/22/17 09:05:22 PM   tasks.py: 98]  INFO Map chosen for this game: Map object
[02/22/17 09:05:22 PM   tasks.py:104]  INFO Created game id: 28
[02/22/17 09:05:22 PM   tasks.py:108] DEBUG Updating game_user entries
[02/22/17 09:05:22 PM   tasks.py:124] DEBUG Updating each player's unit entries
[02/22/17 09:05:22 PM   tasks.py:131] DEBUG Deleting players from the queue
[02/22/17 09:05:22 PM testhelper: 62] DEBUG Chn.name=Test
[02/22/17 09:05:22 PM  router.py: 89] DEBUG Parsing incoming json request: 
{"Units": [{"Y": 0, "X": 0, "Name": "Archer"}, {"Y": 0, "X": 1, "Name": "Armor"}, {"Y": 0, "X": 2, "Name": "Cleric"}, {"Y": 0, "X": 3, "Name": "Flier"}, {"Y": 0, "X": 4, "Name": "Horseman"}, {"Y": 0, "X": 5, "Name": "Mage"}, {"Y": 0, "X": 6, "Name": "Rogue"}, {"Y": 0, "X": 7, "Name": "Swordsman"}], "Game": "vs. game_user_2 #1", "Command": "PU"}
[02/22/17 09:05:22 PM  router.py:117] DEBUG Received command: PU
[02/22/17 09:05:22 PM testhelper: 62] DEBUG Chn.name=Test2
[02/22/17 09:05:22 PM  router.py: 89] DEBUG Parsing incoming json request: 
{"Units": [{"Y": 15, "X": 0, "Name": "Archer"}, {"Y": 15, "X": 1, "Name": "Armor"}, {"Y": 15, "X": 2, "Name": "Cleric"}, {"Y": 15, "X": 3, "Name": "Flier"}, {"Y": 15, "X": 4, "Name": "Horseman"}, {"Y": 15, "X": 5, "Name": "Mage"}, {"Y": 15, "X": 6, "Name": "Rogue"}, {"Y": 15, "X": 7, "Name": "Swordsman"}], "Game": "vs. game_user_1 #1", "Command": "PU"}
[02/22/17 09:05:22 PM  router.py:117] DEBUG Received command: PU
[02/22/17 09:05:22 PM   tests.py:644] DEBUG Unit: X: 3	 Y: 0	 ID: 498	 Name: Flier	 Owner: game_user_1
[02/22/17 09:05:22 PM   tests.py:644] DEBUG Unit: X: 1	 Y: 0	 ID: 499	 Name: Armor	 Owner: game_user_1
[02/22/17 09:05:22 PM   tests.py:644] DEBUG Unit: X: 6	 Y: 0	 ID: 500	 Name: Rogue	 Owner: game_user_1
[02/22/17 09:05:22 PM   tests.py:644] DEBUG Unit: X: 4	 Y: 0	 ID: 501	 Name: Horseman	 Owner: game_user_1
[02/22/17 09:05:22 PM   tests.py:644] DEBUG Unit: X: 5	 Y: 0	 ID: 502	 Name: Mage	 Owner: game_user_1
[02/22/17 09:05:22 PM   tests.py:644] DEBUG Unit: X: 7	 Y: 0	 ID: 503	 Name: Swordsman	 Owner: game_user_1
[02/22/17 09:05:22 PM   tests.py:644] DEBUG Unit: X: 2	 Y: 0	 ID: 504	 Name: Cleric	 Owner: game_user_1
[02/22/17 09:05:22 PM   tests.py:644] DEBUG Unit: X: 0	 Y: 0	 ID: 505	 Name: Archer	 Owner: game_user_1
[02/22/17 09:05:22 PM   tests.py:644] DEBUG Unit: X: 3	 Y: 15	 ID: 506	 Name: Flier	 Owner: game_user_2
[02/22/17 09:05:22 PM   tests.py:644] DEBUG Unit: X: 1	 Y: 15	 ID: 507	 Name: Armor	 Owner: game_user_2
[02/22/17 09:05:22 PM   tests.py:644] DEBUG Unit: X: 6	 Y: 15	 ID: 508	 Name: Rogue	 Owner: game_user_2
[02/22/17 09:05:22 PM   tests.py:644] DEBUG Unit: X: 4	 Y: 15	 ID: 509	 Name: Horseman	 Owner: game_user_2
[02/22/17 09:05:22 PM   tests.py:644] DEBUG Unit: X: 5	 Y: 15	 ID: 510	 Name: Mage	 Owner: game_user_2
[02/22/17 09:05:22 PM   tests.py:644] DEBUG Unit: X: 7	 Y: 15	 ID: 511	 Name: Swordsman	 Owner: game_user_2
[02/22/17 09:05:22 PM   tests.py:644] DEBUG Unit: X: 2	 Y: 15	 ID: 512	 Name: Cleric	 Owner: game_user_2
[02/22/17 09:05:22 PM   tests.py:644] DEBUG Unit: X: 0	 Y: 15	 ID: 513	 Name: Archer	 Owner: game_user_2
[02/22/17 09:05:22 PM testhelper: 62] DEBUG Chn.name=Test
[02/22/17 09:05:22 PM  router.py: 89] DEBUG Parsing incoming json request: 
{"Target": 504, "Action": "Heal", "Game": "vs. game_user_2 #1", "Command": "TA", "Y": 0, "X": 2, "Unit": 504}
[02/22/17 09:05:22 PM  router.py:117] DEBUG Received command: TA
[02/22/17 09:05:22 PM unithelper:396] DEBUG Unit Locations {0: {0: 'Ally', 15: 'Enemy'}, 1: {0: 'Ally', 15: 'Enemy'}, 2: {15: 'Enemy'}, 3: {0: 'Ally', 15: 'Enemy'}, 4: {0: 'Ally', 15: 'Enemy'}, 5: {0: 'Ally', 15: 'Enemy'}, 6: {0: 'Ally', 15: 'Enemy'}, 7: {0: 'Ally', 15: 'Enemy'}}
[02/22/17 09:05:22 PM unithelper:402] DEBUG Attempting to move Cleric from location (2,0) to location (2,0).
[02/22/17 09:05:22 PM unithelper:428] DEBUG Checking location (2,0).
[02/22/17 09:05:22 PM unithelper:451] DEBUG SUCCESS! Can move to (2,0).
[02/22/17 09:05:22 PM routehelpe: 50] ERROR Cannot target self.:
{u'Target': 504, 'session_username': u'game_user_1', u'Y': 0, u'Game': u'vs. game_user_2 #1', u'Command': u'TA', u'Action': u'Heal', u'X': 2, u'Unit': 504}
[02/22/17 09:05:22 PM testhelper:173] DEBUG ============ Finishing Test: test_ta_17_heal_fully_success ============
