### ISSUE TITLE
Travis Failure: test_ta_19_heal_exact_full_success

### ISSUE THREAD

**Issue by akkowal2** [DBN16CO/Tactics#169]
https://travis-ci.org/DBN16CO/Tactics/builds/222474237
```
======================================================================
FAIL: test_ta_19_heal_exact_full_success (Game.tests.TestTakeAction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/DBN16CO/Tactics/Server/Game/tests.py", line 1388, in test_ta_19_heal_exact_full_success
    result, unit, tgt, heal_data = self.helper_execute_heal_success(self.heal_cmd)
  File "/home/travis/build/DBN16CO/Tactics/Server/Game/tests.py", line 791, in helper_execute_heal_success
    result = self.helper_execute_move_success(command)
  File "/home/travis/build/DBN16CO/Tactics/Server/Game/tests.py", line 739, in helper_execute_move_success
    result = self.helper_execute_success(command)
  File "/home/travis/build/DBN16CO/Tactics/Server/Communication/testhelper.py", line 211, in helper_execute_success
    self.assertTrue(result["Success"])
AssertionError: False is not true
```

Log:
```
[04/15/17 09:01:34 PM testhelper:167] DEBUG ============  Starting Test: test_ta_19_heal_exact_full_success ============
[04/15/17 09:01:34 PM create_dat: 34]  INFO Creating Version object...
[04/15/17 09:01:34 PM create_dat: 40]  INFO Creating Ability objects...
[04/15/17 09:01:34 PM create_dat: 46]  INFO Creating Action objects...
[04/15/17 09:01:34 PM create_dat: 52]  INFO Creating Leader objects...
[04/15/17 09:01:34 PM create_dat: 62]  INFO Creating Perk objects...
[04/15/17 09:01:34 PM create_dat: 69]  INFO Creating Map objects...
[04/15/17 09:01:34 PM create_dat: 75]  INFO Creating Stat objects...
[04/15/17 09:01:34 PM create_dat: 81]  INFO Creating Terrain objects...
[04/15/17 09:01:34 PM create_dat: 88]  INFO Creating Class objects...
[04/15/17 09:01:34 PM maphelper.:114] DEBUG Movement Dictionary:
[04/15/17 09:01:34 PM maphelper.:115] DEBUG {u'R': {u'Cleric': 1, u'Flier': 1, u'Archer': 1, u'Armor': 1, u'Swordsman': 1, u'Rogue': 1, u'Horseman': 1, u'Mage': 1}, u'M': {u'Cleric': 3, u'Flier': 1, u'Archer': 4, u'Armor': 99, u'Swordsman': 4, u'Rogue': 2, u'Horseman': 99, u'Mage': 3}, u'G': {u'Cleric': 1, u'Flier': 1, u'Archer': 1, u'Armor': 1, u'Swordsman': 1, u'Rogue': 1, u'Horseman': 1, u'Mage': 1}, u'W': {u'Cleric': 99, u'Flier': 1, u'Archer': 99, u'Armor': 99, u'Swordsman': 99, u'Rogue': 99, u'Horseman': 99, u'Mage': 99}, u'F': {u'Cleric': 2, u'Flier': 1, u'Archer': 2, u'Armor': 3, u'Swordsman': 3, u'Rogue': 1, u'Horseman': 3, u'Mage': 2}}
[04/15/17 09:01:34 PM testhelper:100] DEBUG {"username": "game_user_1", "Command": "CU", "pw": "aaaaaaa", "email": "userOne@email.com"}
[04/15/17 09:01:34 PM testhelper: 62] DEBUG Chn.name=Test
[04/15/17 09:01:34 PM  router.py: 89] DEBUG Parsing incoming json request: 
{"username": "game_user_1", "Command": "CU", "pw": "aaaaaaa", "email": "userOne@email.com"}
[04/15/17 09:01:34 PM  router.py:117] DEBUG Received command: CU
[04/15/17 09:01:35 PM  router.py:204] DEBUG Response: {'Token': '39b309e2ddc2434993ed367f61ba05c7', 'Success': True}
[04/15/17 09:01:35 PM testhelper:103] DEBUG {"Token": "39b309e2ddc2434993ed367f61ba05c7", "Success": true}
[04/15/17 09:01:35 PM testhelper: 62] DEBUG Chn.name=Test
[04/15/17 09:01:35 PM  router.py: 89] DEBUG Parsing incoming json request: 
{"username": "game_user_1", "Command": "LGN", "pw": "aaaaaaa"}
[04/15/17 09:01:35 PM  router.py:117] DEBUG Received command: LGN
[04/15/17 09:01:35 PM  router.py:204] DEBUG Response: {'Token': 'aa4aa2f2fe864fc4a206def7e85d5de9', 'Success': True}
[04/15/17 09:01:35 PM testhelper: 62] DEBUG Chn.name=Test
[04/15/17 09:01:35 PM  router.py: 89] DEBUG Parsing incoming json request: 
{"Units": ["Flier", "Armor", "Rogue", "Horseman", "Mage", "Swordsman", "Cleric", "Archer"], "Perks": [], "Command": "ST", "Ability": "Extra Range", "Leader": "Sniper"}
[04/15/17 09:01:35 PM  router.py:117] DEBUG Received command: ST
[04/15/17 09:01:35 PM statichelp:117] DEBUG Loading Version data...
[04/15/17 09:01:35 PM statichelp:119] DEBUG Using latest version: 1.0
[04/15/17 09:01:35 PM statichelp:122] DEBUG Loading Ability data...
[04/15/17 09:01:35 PM statichelp:207] DEBUG There are 4 objects in ability for version 1.0.
[04/15/17 09:01:35 PM statichelp:128] DEBUG Loading Action data...
[04/15/17 09:01:35 PM statichelp:234] DEBUG There are 3 objects in action for version 1.0.
[04/15/17 09:01:35 PM statichelp:134] DEBUG Loading Class data...
[04/15/17 09:01:35 PM statichelp:270] DEBUG There are 8 objects in class for version 1.0.
[04/15/17 09:01:35 PM statichelp:293] DEBUG There are 9 objects in Unit_Stat for class Flier version 1.0.
[04/15/17 09:01:35 PM statichelp:300] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Flier version 1.0.
[04/15/17 09:01:35 PM statichelp:293] DEBUG There are 9 objects in Unit_Stat for class Armor version 1.0.
[04/15/17 09:01:35 PM statichelp:300] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Armor version 1.0.
[04/15/17 09:01:35 PM statichelp:293] DEBUG There are 9 objects in Unit_Stat for class Rogue version 1.0.
[04/15/17 09:01:35 PM statichelp:300] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Rogue version 1.0.
[04/15/17 09:01:35 PM statichelp:293] DEBUG There are 9 objects in Unit_Stat for class Horseman version 1.0.
[04/15/17 09:01:35 PM statichelp:300] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Horseman version 1.0.
[04/15/17 09:01:35 PM statichelp:293] DEBUG There are 9 objects in Unit_Stat for class Mage version 1.0.
[04/15/17 09:01:35 PM statichelp:300] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Mage version 1.0.
[04/15/17 09:01:35 PM statichelp:293] DEBUG There are 9 objects in Unit_Stat for class Swordsman version 1.0.
[04/15/17 09:01:35 PM statichelp:300] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Swordsman version 1.0.
[04/15/17 09:01:35 PM statichelp:293] DEBUG There are 9 objects in Unit_Stat for class Cleric version 1.0.
[04/15/17 09:01:35 PM statichelp:300] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Cleric version 1.0.
[04/15/17 09:01:35 PM statichelp:293] DEBUG There are 9 objects in Unit_Stat for class Archer version 1.0.
[04/15/17 09:01:35 PM statichelp:300] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Archer version 1.0.
[04/15/17 09:01:35 PM statichelp:140] DEBUG Loading Leader data...
[04/15/17 09:01:35 PM statichelp:328] DEBUG There are 5 objects in leader for version 1.0.
[04/15/17 09:01:35 PM statichelp:146] DEBUG Loading Map data...
[04/15/17 09:01:35 PM statichelp:365] DEBUG There are 2 objects in map for version 1.0.
[04/15/17 09:01:35 PM statichelp:152] DEBUG Loading Perk data...
[04/15/17 09:01:35 PM statichelp:411] DEBUG There are 4 objects in perk for version 1.0.
[04/15/17 09:01:35 PM statichelp:158] DEBUG Loading Stat data...
[04/15/17 09:01:35 PM statichelp:444] DEBUG There are 9 objects in stat for version 1.0.
[04/15/17 09:01:35 PM statichelp:164] DEBUG Loading Terrain data...
[04/15/17 09:01:35 PM statichelp:479] DEBUG There are 5 objects in terrain for version 1.0.
[04/15/17 09:01:35 PM  router.py:204] DEBUG Response: {'Success': True}
[04/15/17 09:01:35 PM testhelper: 62] DEBUG Chn.name=Test
[04/15/17 09:01:35 PM  router.py: 89] DEBUG Parsing incoming json request: 
{"Command": "FM"}
[04/15/17 09:01:35 PM  router.py:117] DEBUG Received command: FM
[04/15/17 09:01:35 PM  router.py:156] DEBUG Adding channel name to JSON: Test
[04/15/17 09:01:35 PM  router.py:204] DEBUG Response: {'Success': True}
[04/15/17 09:01:35 PM testhelper:100] DEBUG {"username": "game_user_2", "Command": "CU", "pw": "aaaaaaa", "email": "userTwo@email.com"}
[04/15/17 09:01:35 PM testhelper: 62] DEBUG Chn.name=Test2
[04/15/17 09:01:35 PM  router.py: 89] DEBUG Parsing incoming json request: 
{"username": "game_user_2", "Command": "CU", "pw": "aaaaaaa", "email": "userTwo@email.com"}
[04/15/17 09:01:35 PM  router.py:117] DEBUG Received command: CU
[04/15/17 09:01:36 PM  router.py:204] DEBUG Response: {'Token': '1fec9180a2104138a25a885ff0d1d7c4', 'Success': True}
[04/15/17 09:01:36 PM testhelper:103] DEBUG {"Token": "1fec9180a2104138a25a885ff0d1d7c4", "Success": true}
[04/15/17 09:01:36 PM testhelper: 62] DEBUG Chn.name=Test2
[04/15/17 09:01:36 PM  router.py: 89] DEBUG Parsing incoming json request: 
{"username": "game_user_2", "Command": "LGN", "pw": "aaaaaaa"}
[04/15/17 09:01:36 PM  router.py:117] DEBUG Received command: LGN
[04/15/17 09:01:36 PM  router.py:204] DEBUG Response: {'Token': '1a1b8a508b4b49078c033a40bc54552c', 'Success': True}
[04/15/17 09:01:36 PM testhelper: 62] DEBUG Chn.name=Test2
[04/15/17 09:01:36 PM  router.py: 89] DEBUG Parsing incoming json request: 
{"Units": ["Flier", "Armor", "Rogue", "Horseman", "Mage", "Swordsman", "Cleric", "Archer"], "Perks": [], "Command": "ST", "Ability": "Extra Range", "Leader": "Sniper"}
[04/15/17 09:01:36 PM  router.py:117] DEBUG Received command: ST
[04/15/17 09:01:36 PM  router.py:204] DEBUG Response: {'Success': True}
[04/15/17 09:01:36 PM testhelper: 62] DEBUG Chn.name=Test2
[04/15/17 09:01:36 PM  router.py: 89] DEBUG Parsing incoming json request: 
{"Command": "FM"}
[04/15/17 09:01:36 PM  router.py:117] DEBUG Received command: FM
[04/15/17 09:01:36 PM  router.py:156] DEBUG Adding channel name to JSON: Test2
[04/15/17 09:01:36 PM  router.py:204] DEBUG Response: {'Success': True}
[04/15/17 09:01:36 PM   tasks.py: 49] DEBUG Processing matchmaking queue
[04/15/17 09:01:36 PM   tasks.py: 70]  INFO Found a match: game_user_1 vs. game_user_2
[04/15/17 09:01:36 PM   tasks.py: 82]  INFO Users have played each other 0 times.
[04/15/17 09:01:36 PM   tasks.py: 91]  INFO game_user_2 will take the first turn
[04/15/17 09:01:36 PM   tasks.py:100]  INFO Map chosen for this game: Map object
[04/15/17 09:01:36 PM   tasks.py:109]  INFO Created game id: 31
[04/15/17 09:01:36 PM   tasks.py:113] DEBUG Updating game_user entries
[04/15/17 09:01:36 PM   tasks.py:129] DEBUG Updating each player's unit entries
[04/15/17 09:01:36 PM   tasks.py:136] DEBUG Deleting players from the queue
[04/15/17 09:01:36 PM testhelper: 62] DEBUG Chn.name=Test
[04/15/17 09:01:36 PM  router.py: 89] DEBUG Parsing incoming json request: 
{"Units": [{"Y": 0, "X": 0, "Name": "Archer"}, {"Y": 0, "X": 1, "Name": "Armor"}, {"Y": 0, "X": 2, "Name": "Cleric"}, {"Y": 0, "X": 3, "Name": "Flier"}, {"Y": 0, "X": 4, "Name": "Horseman"}, {"Y": 0, "X": 5, "Name": "Mage"}, {"Y": 0, "X": 6, "Name": "Rogue"}, {"Y": 0, "X": 7, "Name": "Swordsman"}], "Game": "vs. game_user_2 #1", "Command": "PU"}
[04/15/17 09:01:36 PM  router.py:117] DEBUG Received command: PU
[04/15/17 09:01:36 PM  router.py:204] DEBUG Response: {'Success': True}
[04/15/17 09:01:36 PM testhelper: 62] DEBUG Chn.name=Test2
[04/15/17 09:01:36 PM  router.py: 89] DEBUG Parsing incoming json request: 
{"Units": [{"Y": 15, "X": 0, "Name": "Archer"}, {"Y": 15, "X": 1, "Name": "Armor"}, {"Y": 15, "X": 2, "Name": "Cleric"}, {"Y": 15, "X": 3, "Name": "Flier"}, {"Y": 15, "X": 4, "Name": "Horseman"}, {"Y": 15, "X": 5, "Name": "Mage"}, {"Y": 15, "X": 6, "Name": "Rogue"}, {"Y": 15, "X": 7, "Name": "Swordsman"}], "Game": "vs. game_user_1 #1", "Command": "PU"}
[04/15/17 09:01:36 PM  router.py:117] DEBUG Received command: PU
[04/15/17 09:01:36 PM  router.py:204] DEBUG Response: {'Success': True}
[04/15/17 09:01:36 PM   tests.py:677] DEBUG Unit: X: 3	 Y: 0	 ID: 562	 Name: Flier	 Owner: game_user_1
[04/15/17 09:01:36 PM   tests.py:677] DEBUG Unit: X: 1	 Y: 0	 ID: 563	 Name: Armor	 Owner: game_user_1
[04/15/17 09:01:36 PM   tests.py:677] DEBUG Unit: X: 6	 Y: 0	 ID: 564	 Name: Rogue	 Owner: game_user_1
[04/15/17 09:01:36 PM   tests.py:677] DEBUG Unit: X: 4	 Y: 0	 ID: 565	 Name: Horseman	 Owner: game_user_1
[04/15/17 09:01:36 PM   tests.py:677] DEBUG Unit: X: 5	 Y: 0	 ID: 566	 Name: Mage	 Owner: game_user_1
[04/15/17 09:01:36 PM   tests.py:677] DEBUG Unit: X: 7	 Y: 0	 ID: 567	 Name: Swordsman	 Owner: game_user_1
[04/15/17 09:01:36 PM   tests.py:677] DEBUG Unit: X: 2	 Y: 0	 ID: 568	 Name: Cleric	 Owner: game_user_1
[04/15/17 09:01:36 PM   tests.py:677] DEBUG Unit: X: 0	 Y: 0	 ID: 569	 Name: Archer	 Owner: game_user_1
[04/15/17 09:01:36 PM   tests.py:677] DEBUG Unit: X: 3	 Y: 15	 ID: 570	 Name: Flier	 Owner: game_user_2
[04/15/17 09:01:36 PM   tests.py:677] DEBUG Unit: X: 1	 Y: 15	 ID: 571	 Name: Armor	 Owner: game_user_2
[04/15/17 09:01:36 PM   tests.py:677] DEBUG Unit: X: 6	 Y: 15	 ID: 572	 Name: Rogue	 Owner: game_user_2
[04/15/17 09:01:36 PM   tests.py:677] DEBUG Unit: X: 4	 Y: 15	 ID: 573	 Name: Horseman	 Owner: game_user_2
[04/15/17 09:01:36 PM   tests.py:677] DEBUG Unit: X: 5	 Y: 15	 ID: 574	 Name: Mage	 Owner: game_user_2
[04/15/17 09:01:36 PM   tests.py:677] DEBUG Unit: X: 7	 Y: 15	 ID: 575	 Name: Swordsman	 Owner: game_user_2
[04/15/17 09:01:36 PM   tests.py:677] DEBUG Unit: X: 2	 Y: 15	 ID: 576	 Name: Cleric	 Owner: game_user_2
[04/15/17 09:01:36 PM   tests.py:677] DEBUG Unit: X: 0	 Y: 15	 ID: 577	 Name: Archer	 Owner: game_user_2
[04/15/17 09:01:36 PM testhelper: 62] DEBUG Chn.name=Test
[04/15/17 09:01:36 PM  router.py: 89] DEBUG Parsing incoming json request: 
{"Target": 568, "Action": "Heal", "Game": "vs. game_user_2 #1", "Command": "TA", "Y": 0, "X": 2, "Unit": 568}
[04/15/17 09:01:36 PM  router.py:117] DEBUG Received command: TA
[04/15/17 09:01:36 PM unithelper:398] DEBUG Unit Locations {0: {0: 'Ally', 15: 'Enemy'}, 1: {0: 'Ally', 15: 'Enemy'}, 2: {15: 'Enemy'}, 3: {0: 'Ally', 15: 'Enemy'}, 4: {0: 'Ally', 15: 'Enemy'}, 5: {0: 'Ally', 15: 'Enemy'}, 6: {0: 'Ally', 15: 'Enemy'}, 7: {0: 'Ally', 15: 'Enemy'}}
[04/15/17 09:01:36 PM unithelper:404] DEBUG Attempting to move Cleric from location (2,0) to location (2,0).
[04/15/17 09:01:36 PM unithelper:430] DEBUG Checking location (2,0).
[04/15/17 09:01:36 PM unithelper:453] DEBUG SUCCESS! Can move to (2,0).
[04/15/17 09:01:36 PM routehelpe: 50] ERROR Cannot target self.:
{u'Target': 568, 'session_username': u'game_user_1', u'Y': 0, u'Game': u'vs. game_user_2 #1', u'Command': u'TA', u'Action': u'Heal', u'X': 2, u'Unit': 568}
[04/15/17 09:01:36 PM  router.py:204] DEBUG Response: {'Success': False, 'Error': 'Cannot target self.'}
[04/15/17 09:01:36 PM testhelper:173] DEBUG ============ Finishing Test: test_ta_19_heal_exact_full_success ============
```

**Comment by DaBernMon** [comment]
Should be fixed in PR #183.  
  
The problem (if you look at the  logs above, the proof should be clear) was that the healer and its target was the same unit.  This is possible due to the way the target was determined.  The target was the closest unit to the attacker unit.  By normal execution the database should add units alphabetically.  By those means the first unit is an archer (the attacker) and the third unit is a cleric (the healer).  Thus the tests would conveniently typically pass because the unit in between the two (the armor) was nearest to both of them.  The nearest unit determination is now separated for both attacker and healer.
