### ISSUE TITLE
test_ta_12_crit_attack_success test Failed

### ISSUE THREAD

**Issue by akkowal2** [DBN16CO/Tactics#188]
```
Drews-MBP:Server Drew$ coverage run manage.py test
nosetests --with-coverage --cover-package=Communication,Game,Static,User --cover-inclusive --cover-erase --cover-html --nocapture --nologcapture --verbosity=3
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
nose.plugins.cover: INFO: Coverage report will include only packages: ['Communication', 'Game', 'Static', 'User']
Creating test database for alias 'default'...
nose.selector: INFO: /Users/Drew/Projects/Tactics/Server/manage.py is executable; skipped
test_cm_01_ping_server (Communication.tests.TestCommunication) ... ok
test_cm_02_internal_error (Communication.tests.TestCommunication) ... ok
test_cm_03_missing_command (Communication.tests.TestCommunication) ... ok
test_cm_04_invalid_json (Communication.tests.TestCommunication) ... ok
test_cm_05_unauthenthicated_access (Communication.tests.TestCommunication) ... ok
test_cm_06_reload_static_maps (Communication.tests.TestCommunication) ... ok
test_rm_01_received_message_success (Communication.tests.TestReceivedMessage) ... ok
test_rm_02_received_message_incorrect_message_id (Communication.tests.TestReceivedMessage) ... ok
test_rm_03_async_message_expiration (Communication.tests.TestReceivedMessage) ... ok
test_et_01_bad_json (Game.tests.TestEndTurn) ... ok
test_et_02_not_turn (Game.tests.TestEndTurn) ... ok
test_et_03_success (Game.tests.TestEndTurn) ... ok
test_fm_01_before_set_team (Game.tests.TestFindMatch) ... ok
test_fm_02_find_match_success (Game.tests.TestFindMatch) ... ok
test_fm_03_already_in_queue (Game.tests.TestFindMatch) ... ok
test_fm_04_cancel_search_success (Game.tests.TestFindMatch) ... ok
test_mm_01_pair_success (Game.tests.TestMatchmaking) ... ok
test_mm_02_one_user_test (Game.tests.TestMatchmaking) ... ok
test_mm_03_two_games_matched (Game.tests.TestMatchmaking) ... ok
test_mm_04_matchmaking_exception_rollback (Game.tests.TestMatchmaking) ... ok
test_pu_01_bad_json (Game.tests.TestPlaceUnits) ... ok
test_pu_02_success (Game.tests.TestPlaceUnits) ... ok
test_pu_03_not_matched (Game.tests.TestPlaceUnits) ... ok
test_qgu_01_one_game_one_opponent (Game.tests.TestQueryGames) ... ok
test_qgu_02_set_team_not_matched (Game.tests.TestQueryGames) ... ok
test_qgu_03_action_history_correct (Game.tests.TestQueryGames) ... ok
test_st_01_bad_json (Game.tests.TestSetTeam) ... ok
test_st_02_price_max_exceeded (Game.tests.TestSetTeam) ... ok
test_st_03_multiple_same_tier_perks (Game.tests.TestSetTeam) ... ok
test_st_04_valid_input (Game.tests.TestSetTeam) ... ok
test_st_05_repeat_command (Game.tests.TestSetTeam) ... ok
test_st_06_already_in_queue (Game.tests.TestSetTeam) ... ok
test_ta_01_bad_json (Game.tests.TestTakeAction) ... ok
test_ta_02_bad_move (Game.tests.TestTakeAction) ... ok
test_ta_03_move_on_self_success (Game.tests.TestTakeAction) ... ok
test_ta_04_partial_move_success (Game.tests.TestTakeAction) ... ok
test_ta_05_full_move_success (Game.tests.TestTakeAction) ... ok
test_ta_06_move_through_ally_success (Game.tests.TestTakeAction) ... ok
test_ta_07_before_enemy_placement (Game.tests.TestTakeAction) ... ok
test_ta_08_before_own_placement (Game.tests.TestTakeAction) ... ok
test_ta_09_basic_attack_success (Game.tests.TestTakeAction) ... ok
test_ta_10_bad_heal (Game.tests.TestTakeAction) ... ok
test_ta_11_bad_attack (Game.tests.TestTakeAction) ... ok
test_ta_12_crit_attack_success (Game.tests.TestTakeAction) ... FAIL
test_ta_13_attack_no_counter_success (Game.tests.TestTakeAction) ... ok
test_ta_14_attack_miss_success (Game.tests.TestTakeAction) ... ok
test_ta_15_tgt_passive_success (Game.tests.TestTakeAction) ... ok
test_ta_16_counter_misses_success (Game.tests.TestTakeAction) ... ok
test_ta_17_heal_fully_success (Game.tests.TestTakeAction) ... ok
test_ta_18_heal_partial_success (Game.tests.TestTakeAction) ... ok
test_ta_19_heal_exact_full_success (Game.tests.TestTakeAction) ... ok
test_ta_20_act_on_enemy_turn (Game.tests.TestTakeAction) ... ok
test_ta_21_magical_counterattack (Game.tests.TestTakeAction) ... ok
test_db_01_bad_db_setup (Static.tests.TestStatic) ... ok
test_il_02_v1_0 (Static.tests.TestStatic) ... ok
test_il_03_incomplete_version (Static.tests.TestStatic) ... ok
test_cu_01_create_user_success (User.tests.TestCreateUser) ... ok
test_cu_02_duplicate_username (User.tests.TestCreateUser) ... ok
test_cu_03_duplicate_email (User.tests.TestCreateUser) ... ok
test_cu_04_invalid_email_address (User.tests.TestCreateUser) ... ok
test_cu_05_invalid_username (User.tests.TestCreateUser) ... ok
test_cu_06_missing_values (User.tests.TestCreateUser) ... ok
test_cu_07_password_policy_failures (User.tests.TestCreateUser) ... ok
test_lo_01_in_success_username_password (User.tests.TestLoginLogout) ... ok
test_lo_02_in_failure_username_password (User.tests.TestLoginLogout) ... ok
test_lo_03_in_success_token (User.tests.TestLoginLogout) ... ok
test_lo_04_in_failure_token (User.tests.TestLoginLogout) ... ok
test_lo_05_out_success (User.tests.TestLoginLogout) ... ok
test_lo_06_out_failure (User.tests.TestLoginLogout) ... ok
test_lo_07_get_user_info_success (User.tests.TestLoginLogout) ... ok
test_lo_08_login_token_expire (User.tests.TestLoginLogout) ... ok

======================================================================
FAIL: test_ta_12_crit_attack_success (Game.tests.TestTakeAction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Drew/Projects/Tactics/Server/Game/tests.py", line 1451, in test_ta_12_crit_attack_success
    self.helper_verify_crit_miss(result, unit, tgt, attack_data, action_history, crit_miss)
  File "/Users/Drew/Projects/Tactics/Server/Game/tests.py", line 992, in helper_verify_crit_miss
    self.assertFalse(action_history.tgt_counter)
AssertionError: True is not false
```

Log:
```
[06/09/17 08:44:30 PM testhelper:179] DEBUG ============  Starting Test: test_ta_12_crit_attack_success ============
[06/09/17 08:44:30 PM create_dat: 34]  INFO Creating Version object...
[06/09/17 08:44:30 PM create_dat: 40]  INFO Creating Ability objects...
[06/09/17 08:44:30 PM create_dat: 46]  INFO Creating Action objects...
[06/09/17 08:44:30 PM create_dat: 52]  INFO Creating Leader objects...
[06/09/17 08:44:30 PM create_dat: 62]  INFO Creating Perk objects...
[06/09/17 08:44:30 PM create_dat: 69]  INFO Creating Map objects...
[06/09/17 08:44:30 PM create_dat: 75]  INFO Creating Stat objects...
[06/09/17 08:44:30 PM create_dat: 81]  INFO Creating Terrain objects...
[06/09/17 08:44:30 PM create_dat: 88]  INFO Creating Class objects...
[06/09/17 08:44:30 PM maphelper.:114] DEBUG Movement Dictionary:
[06/09/17 08:44:30 PM maphelper.:115] DEBUG {u'R': {u'Cleric': 1, u'Flier': 1, u'Archer': 1, u'Armor': 1, u'Swordsman': 1, u'Rogue': 1, u'Horseman': 1, u'Mage': 1}, u'M': {u'Cleric': 3, u'Flier': 1, u'Archer': 4, u'Armor': 99, u'Swordsman': 4, u'Rogue': 2, u'Horseman': 99, u'Mage': 3}, u'G': {u'Cleric': 1, u'Flier': 1, u'Archer': 1, u'Armor': 1, u'Swordsman': 1, u'Rogue': 1, u'Horseman': 1, u'Mage': 1}, u'W': {u'Cleric': 99, u'Flier': 1, u'Archer': 99, u'Armor': 99, u'Swordsman': 99, u'Rogue': 99, u'Horseman': 99, u'Mage': 99}, u'F': {u'Cleric': 2, u'Flier': 1, u'Archer': 2, u'Armor': 3, u'Swordsman': 3, u'Rogue': 1, u'Horseman': 3, u'Mage': 2}}
[06/09/17 08:44:30 PM testhelper:112] DEBUG {"username": "game_user_1", "Command": "CU", "pw": "aaaaaaa", "email": "userOne@email.com"}
[06/09/17 08:44:30 PM testhelper: 74] DEBUG Chn.name=Test
[06/09/17 08:44:30 PM  router.py:102] DEBUG Parsing incoming json request: 
{"username": "game_user_1", "Command": "CU", "pw": "aaaaaaa", "email": "userOne@email.com"}
[06/09/17 08:44:30 PM  router.py:142] DEBUG Received command: CU
[06/09/17 08:44:30 PM  router.py:189] DEBUG Adding channel name to JSON: Test1
[06/09/17 08:44:30 PM  router.py:247] DEBUG Response: {'Token': 'c5814675bc714e2588ea810b3a0a8de3', 'Success': True}
[06/09/17 08:44:30 PM testhelper:115] DEBUG {"Token": "c5814675bc714e2588ea810b3a0a8de3", "Success": true}
[06/09/17 08:44:30 PM testhelper: 74] DEBUG Chn.name=Test
[06/09/17 08:44:30 PM  router.py:102] DEBUG Parsing incoming json request: 
{"username": "game_user_1", "Command": "LGN", "pw": "aaaaaaa"}
[06/09/17 08:44:30 PM  router.py:142] DEBUG Received command: LGN
[06/09/17 08:44:30 PM  router.py:189] DEBUG Adding channel name to JSON: Test1
[06/09/17 08:44:31 PM  router.py:247] DEBUG Response: {'Token': '180769d10527481e9b39e97af4ee322e', 'Success': True}
[06/09/17 08:44:31 PM testhelper: 74] DEBUG Chn.name=Test
[06/09/17 08:44:31 PM  router.py:102] DEBUG Parsing incoming json request: 
{"Ability": "Extra Range", "Perks": [], "Command": "ST", "Request_ID": "0", "Units": ["Horseman", "Mage", "Swordsman", "Cleric", "Archer", "Flier", "Armor", "Rogue"], "Leader": "Sniper"}
[06/09/17 08:44:31 PM  router.py:142] DEBUG Received command: ST
[06/09/17 08:44:31 PM statichelp:120] DEBUG Loading Version data...
[06/09/17 08:44:31 PM statichelp:122] DEBUG Using latest version: 1.0
[06/09/17 08:44:31 PM statichelp:125] DEBUG Loading Ability data...
[06/09/17 08:44:31 PM statichelp:210] DEBUG There are 4 objects in ability for version 1.0.
[06/09/17 08:44:31 PM statichelp:131] DEBUG Loading Action data...
[06/09/17 08:44:31 PM statichelp:237] DEBUG There are 3 objects in action for version 1.0.
[06/09/17 08:44:31 PM statichelp:137] DEBUG Loading Class data...
[06/09/17 08:44:31 PM statichelp:275] DEBUG There are 8 objects in class for version 1.0.
[06/09/17 08:44:31 PM statichelp:298] DEBUG There are 9 objects in Unit_Stat for class Horseman version 1.0.
[06/09/17 08:44:31 PM statichelp:305] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Horseman version 1.0.
[06/09/17 08:44:31 PM statichelp:298] DEBUG There are 9 objects in Unit_Stat for class Mage version 1.0.
[06/09/17 08:44:31 PM statichelp:305] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Mage version 1.0.
[06/09/17 08:44:31 PM statichelp:298] DEBUG There are 9 objects in Unit_Stat for class Swordsman version 1.0.
[06/09/17 08:44:31 PM statichelp:305] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Swordsman version 1.0.
[06/09/17 08:44:31 PM statichelp:298] DEBUG There are 9 objects in Unit_Stat for class Cleric version 1.0.
[06/09/17 08:44:31 PM statichelp:305] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Cleric version 1.0.
[06/09/17 08:44:31 PM statichelp:298] DEBUG There are 9 objects in Unit_Stat for class Archer version 1.0.
[06/09/17 08:44:31 PM statichelp:305] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Archer version 1.0.
[06/09/17 08:44:31 PM statichelp:298] DEBUG There are 9 objects in Unit_Stat for class Flier version 1.0.
[06/09/17 08:44:31 PM statichelp:305] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Flier version 1.0.
[06/09/17 08:44:31 PM statichelp:298] DEBUG There are 9 objects in Unit_Stat for class Armor version 1.0.
[06/09/17 08:44:31 PM statichelp:305] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Armor version 1.0.
[06/09/17 08:44:31 PM statichelp:298] DEBUG There are 9 objects in Unit_Stat for class Rogue version 1.0.
[06/09/17 08:44:31 PM statichelp:305] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Rogue version 1.0.
[06/09/17 08:44:31 PM statichelp:143] DEBUG Loading Leader data...
[06/09/17 08:44:31 PM statichelp:333] DEBUG There are 5 objects in leader for version 1.0.
[06/09/17 08:44:31 PM statichelp:149] DEBUG Loading Map data...
[06/09/17 08:44:31 PM statichelp:370] DEBUG There are 2 objects in map for version 1.0.
[06/09/17 08:44:31 PM statichelp:155] DEBUG Loading Perk data...
[06/09/17 08:44:31 PM statichelp:416] DEBUG There are 4 objects in perk for version 1.0.
[06/09/17 08:44:31 PM statichelp:161] DEBUG Loading Stat data...
[06/09/17 08:44:31 PM statichelp:449] DEBUG There are 9 objects in stat for version 1.0.
[06/09/17 08:44:31 PM statichelp:167] DEBUG Loading Terrain data...
[06/09/17 08:44:31 PM statichelp:484] DEBUG There are 5 objects in terrain for version 1.0.
[06/09/17 08:44:31 PM  router.py:247] DEBUG Response: {'Success': True, 'Request_ID': u'0'}
[06/09/17 08:44:31 PM testhelper: 74] DEBUG Chn.name=Test
[06/09/17 08:44:31 PM  router.py:102] DEBUG Parsing incoming json request: 
{"Command": "FM", "Request_ID": "1"}
[06/09/17 08:44:31 PM  router.py:142] DEBUG Received command: FM
[06/09/17 08:44:31 PM  router.py:247] DEBUG Response: {'Success': True, 'Request_ID': u'1'}
[06/09/17 08:44:31 PM testhelper:112] DEBUG {"username": "game_user_2", "Command": "CU", "pw": "aaaaaaa", "email": "userTwo@email.com"}
[06/09/17 08:44:31 PM testhelper: 74] DEBUG Chn.name=Test2
[06/09/17 08:44:31 PM  router.py:102] DEBUG Parsing incoming json request: 
{"username": "game_user_2", "Command": "CU", "pw": "aaaaaaa", "email": "userTwo@email.com"}
[06/09/17 08:44:31 PM  router.py:142] DEBUG Received command: CU
[06/09/17 08:44:31 PM  router.py:189] DEBUG Adding channel name to JSON: Test22
[06/09/17 08:44:31 PM  router.py:247] DEBUG Response: {'Token': '9f63e430fff84a6f8a5043ba54f58f91', 'Success': True}
[06/09/17 08:44:31 PM testhelper:115] DEBUG {"Token": "9f63e430fff84a6f8a5043ba54f58f91", "Success": true}
[06/09/17 08:44:31 PM testhelper: 74] DEBUG Chn.name=Test2
[06/09/17 08:44:31 PM  router.py:102] DEBUG Parsing incoming json request: 
{"username": "game_user_2", "Command": "LGN", "pw": "aaaaaaa"}
[06/09/17 08:44:31 PM  router.py:142] DEBUG Received command: LGN
[06/09/17 08:44:31 PM  router.py:189] DEBUG Adding channel name to JSON: Test22
[06/09/17 08:44:32 PM  router.py:247] DEBUG Response: {'Token': 'b5e440d36a3e4d15b546d32cd28ae66e', 'Success': True}
[06/09/17 08:44:32 PM testhelper: 74] DEBUG Chn.name=Test2
[06/09/17 08:44:32 PM  router.py:102] DEBUG Parsing incoming json request: 
{"Ability": "Extra Range", "Perks": [], "Command": "ST", "Request_ID": "2", "Units": ["Horseman", "Mage", "Swordsman", "Cleric", "Archer", "Flier", "Armor", "Rogue"], "Leader": "Sniper"}
[06/09/17 08:44:32 PM  router.py:142] DEBUG Received command: ST
[06/09/17 08:44:32 PM  router.py:247] DEBUG Response: {'Success': True, 'Request_ID': u'2'}
[06/09/17 08:44:32 PM testhelper: 74] DEBUG Chn.name=Test2
[06/09/17 08:44:32 PM  router.py:102] DEBUG Parsing incoming json request: 
{"Command": "FM", "Request_ID": "3"}
[06/09/17 08:44:32 PM  router.py:142] DEBUG Received command: FM
[06/09/17 08:44:32 PM  router.py:247] DEBUG Response: {'Success': True, 'Request_ID': u'3'}
[06/09/17 08:44:32 PM   tasks.py: 50] DEBUG Processing matchmaking queue
[06/09/17 08:44:32 PM   tasks.py: 71]  INFO Found a match: game_user_1 vs. game_user_2
[06/09/17 08:44:32 PM   tasks.py: 83]  INFO Users have played each other 0 times.
[06/09/17 08:44:32 PM   tasks.py: 89]  INFO game_user_1 will take the first turn
[06/09/17 08:44:32 PM   tasks.py:101]  INFO Map chosen for this game: Map object
[06/09/17 08:44:32 PM   tasks.py:110]  INFO Created game id: 28
[06/09/17 08:44:32 PM   tasks.py:114] DEBUG Updating game_user entries
[06/09/17 08:44:32 PM   tasks.py:130] DEBUG Updating each player's unit entries
[06/09/17 08:44:32 PM   tasks.py:137] DEBUG Creating async notification messages
[06/09/17 08:44:32 PM   tasks.py:148] DEBUG Deleting players from the queue
[06/09/17 08:44:32 PM testhelper: 74] DEBUG Chn.name=Test
[06/09/17 08:44:32 PM  router.py:102] DEBUG Parsing incoming json request: 
{"Units": [{"Y": 0, "X": 0, "Name": "Archer"}, {"Y": 0, "X": 1, "Name": "Armor"}, {"Y": 0, "X": 2, "Name": "Cleric"}, {"Y": 0, "X": 3, "Name": "Flier"}, {"Y": 0, "X": 4, "Name": "Horseman"}, {"Y": 0, "X": 5, "Name": "Mage"}, {"Y": 0, "X": 6, "Name": "Rogue"}, {"Y": 0, "X": 7, "Name": "Swordsman"}], "Game": "vs. game_user_2 #1", "Command": "PU", "Request_ID": "4"}
[06/09/17 08:44:32 PM  router.py:142] DEBUG Received command: PU
[06/09/17 08:44:32 PM  router.py:247] DEBUG Response: {'Success': True, 'Request_ID': u'4'}
[06/09/17 08:44:32 PM testhelper: 74] DEBUG Chn.name=Test2
[06/09/17 08:44:32 PM  router.py:102] DEBUG Parsing incoming json request: 
{"Units": [{"Y": 15, "X": 0, "Name": "Archer"}, {"Y": 15, "X": 1, "Name": "Armor"}, {"Y": 15, "X": 2, "Name": "Cleric"}, {"Y": 15, "X": 3, "Name": "Flier"}, {"Y": 15, "X": 4, "Name": "Horseman"}, {"Y": 15, "X": 5, "Name": "Mage"}, {"Y": 15, "X": 6, "Name": "Rogue"}, {"Y": 15, "X": 7, "Name": "Swordsman"}], "Game": "vs. game_user_1 #1", "Command": "PU", "Request_ID": "5"}
[06/09/17 08:44:32 PM  router.py:142] DEBUG Received command: PU
[06/09/17 08:44:32 PM  router.py:247] DEBUG Response: {'Success': True, 'Request_ID': u'5'}
[06/09/17 08:44:32 PM   tests.py:778] DEBUG Unit: X: 4	 Y: 0	 ID: 514	 Name: Horseman	 Owner: game_user_1
[06/09/17 08:44:32 PM   tests.py:778] DEBUG Unit: X: 5	 Y: 0	 ID: 515	 Name: Mage	 Owner: game_user_1
[06/09/17 08:44:32 PM   tests.py:778] DEBUG Unit: X: 7	 Y: 0	 ID: 516	 Name: Swordsman	 Owner: game_user_1
[06/09/17 08:44:32 PM   tests.py:778] DEBUG Unit: X: 2	 Y: 0	 ID: 517	 Name: Cleric	 Owner: game_user_1
[06/09/17 08:44:32 PM   tests.py:778] DEBUG Unit: X: 0	 Y: 0	 ID: 518	 Name: Archer	 Owner: game_user_1
[06/09/17 08:44:32 PM   tests.py:778] DEBUG Unit: X: 3	 Y: 0	 ID: 519	 Name: Flier	 Owner: game_user_1
[06/09/17 08:44:32 PM   tests.py:778] DEBUG Unit: X: 1	 Y: 0	 ID: 520	 Name: Armor	 Owner: game_user_1
[06/09/17 08:44:32 PM   tests.py:778] DEBUG Unit: X: 6	 Y: 0	 ID: 521	 Name: Rogue	 Owner: game_user_1
[06/09/17 08:44:32 PM   tests.py:778] DEBUG Unit: X: 4	 Y: 15	 ID: 522	 Name: Horseman	 Owner: game_user_2
[06/09/17 08:44:32 PM   tests.py:778] DEBUG Unit: X: 5	 Y: 15	 ID: 523	 Name: Mage	 Owner: game_user_2
[06/09/17 08:44:32 PM   tests.py:778] DEBUG Unit: X: 7	 Y: 15	 ID: 524	 Name: Swordsman	 Owner: game_user_2
[06/09/17 08:44:32 PM   tests.py:778] DEBUG Unit: X: 2	 Y: 15	 ID: 525	 Name: Cleric	 Owner: game_user_2
[06/09/17 08:44:32 PM   tests.py:778] DEBUG Unit: X: 0	 Y: 15	 ID: 526	 Name: Archer	 Owner: game_user_2
[06/09/17 08:44:32 PM   tests.py:778] DEBUG Unit: X: 3	 Y: 15	 ID: 527	 Name: Flier	 Owner: game_user_2
[06/09/17 08:44:32 PM   tests.py:778] DEBUG Unit: X: 1	 Y: 15	 ID: 528	 Name: Armor	 Owner: game_user_2
[06/09/17 08:44:32 PM   tests.py:778] DEBUG Unit: X: 6	 Y: 15	 ID: 529	 Name: Rogue	 Owner: game_user_2
[06/09/17 08:44:32 PM testhelper: 74] DEBUG Chn.name=Test
[06/09/17 08:44:32 PM  router.py:102] DEBUG Parsing incoming json request: 
{"Target": 524, "Action": "Attack", "Game": "vs. game_user_2 #1", "Command": "TA", "Request_ID": "6", "Y": 14, "X": 7, "Unit": 514}
[06/09/17 08:44:32 PM  router.py:142] DEBUG Received command: TA
[06/09/17 08:44:32 PM statichelp:120] DEBUG Loading Version data...
[06/09/17 08:44:32 PM statichelp:122] DEBUG Using latest version: 1.0
[06/09/17 08:44:32 PM statichelp:125] DEBUG Loading Ability data...
[06/09/17 08:44:32 PM statichelp:210] DEBUG There are 4 objects in ability for version 1.0.
[06/09/17 08:44:32 PM statichelp:131] DEBUG Loading Action data...
[06/09/17 08:44:32 PM statichelp:237] DEBUG There are 3 objects in action for version 1.0.
[06/09/17 08:44:32 PM statichelp:137] DEBUG Loading Class data...
[06/09/17 08:44:32 PM statichelp:275] DEBUG There are 8 objects in class for version 1.0.
[06/09/17 08:44:32 PM statichelp:298] DEBUG There are 9 objects in Unit_Stat for class Horseman version 1.0.
[06/09/17 08:44:32 PM statichelp:305] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Horseman version 1.0.
[06/09/17 08:44:32 PM statichelp:298] DEBUG There are 9 objects in Unit_Stat for class Mage version 1.0.
[06/09/17 08:44:32 PM statichelp:305] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Mage version 1.0.
[06/09/17 08:44:32 PM statichelp:298] DEBUG There are 9 objects in Unit_Stat for class Swordsman version 1.0.
[06/09/17 08:44:32 PM statichelp:305] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Swordsman version 1.0.
[06/09/17 08:44:32 PM statichelp:298] DEBUG There are 9 objects in Unit_Stat for class Cleric version 1.0.
[06/09/17 08:44:32 PM statichelp:305] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Cleric version 1.0.
[06/09/17 08:44:32 PM statichelp:298] DEBUG There are 9 objects in Unit_Stat for class Archer version 1.0.
[06/09/17 08:44:32 PM statichelp:305] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Archer version 1.0.
[06/09/17 08:44:32 PM statichelp:298] DEBUG There are 9 objects in Unit_Stat for class Flier version 1.0.
[06/09/17 08:44:32 PM statichelp:305] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Flier version 1.0.
[06/09/17 08:44:32 PM statichelp:298] DEBUG There are 9 objects in Unit_Stat for class Armor version 1.0.
[06/09/17 08:44:32 PM statichelp:305] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Armor version 1.0.
[06/09/17 08:44:32 PM statichelp:298] DEBUG There are 9 objects in Unit_Stat for class Rogue version 1.0.
[06/09/17 08:44:32 PM statichelp:305] DEBUG There are 5 objects in Terrain_Unit_Movement for class	Rogue version 1.0.
[06/09/17 08:44:32 PM statichelp:143] DEBUG Loading Leader data...
[06/09/17 08:44:32 PM statichelp:333] DEBUG There are 5 objects in leader for version 1.0.
[06/09/17 08:44:32 PM statichelp:149] DEBUG Loading Map data...
[06/09/17 08:44:32 PM statichelp:370] DEBUG There are 2 objects in map for version 1.0.
[06/09/17 08:44:32 PM statichelp:155] DEBUG Loading Perk data...
[06/09/17 08:44:32 PM statichelp:416] DEBUG There are 4 objects in perk for version 1.0.
[06/09/17 08:44:32 PM statichelp:161] DEBUG Loading Stat data...
[06/09/17 08:44:32 PM statichelp:449] DEBUG There are 9 objects in stat for version 1.0.
[06/09/17 08:44:32 PM statichelp:167] DEBUG Loading Terrain data...
[06/09/17 08:44:32 PM statichelp:484] DEBUG There are 5 objects in terrain for version 1.0.
[06/09/17 08:44:32 PM unithelper:448] DEBUG Unit Locations {0: {0: 'Ally', 15: 'Enemy'}, 1: {0: 'Ally', 15: 'Enemy'}, 2: {0: 'Ally', 15: 'Enemy'}, 3: {0: 'Ally', 15: 'Enemy'}, 4: {15: 'Enemy'}, 5: {0: 'Ally', 15: 'Enemy'}, 6: {0: 'Ally', 15: 'Enemy'}, 7: {0: 'Ally', 15: 'Enemy'}}
[06/09/17 08:44:32 PM unithelper:454] DEBUG Attempting to move Horseman from location (7,13) to location (7,14).
[06/09/17 08:44:32 PM unithelper:480] DEBUG Checking location (7,13).
[06/09/17 08:44:32 PM unithelper:480] DEBUG Checking location (7,12).
[06/09/17 08:44:32 PM unithelper:480] DEBUG Checking location (7,14).
[06/09/17 08:44:32 PM unithelper:503] DEBUG SUCCESS! Can move to (7,14).
[06/09/17 08:44:32 PM unithelper:196] DEBUG Attempting action on target 1 away (Range=1).
[06/09/17 08:44:32 PM unithelper:217] DEBUG Horseman[514] attacking 524.
[06/09/17 08:44:32 PM unithelper:239] DEBUG The unit had a critical hit on the target!
[06/09/17 08:44:32 PM unithelper:251] DEBUG Attempting counter attack on unit 1 away (Range=1).
[06/09/17 08:44:32 PM unithelper:285] DEBUG Target's counter attack MISSED!
[06/09/17 08:44:32 PM unithelper:315] DEBUG Result: {'Target': {'NewHP': 8, 'HP': 15, 'Counter': True, 'Crit': False, 'Miss': True, 'ID': 524, 'Unit': <Unit: Unit object>}, 'Unit': {'NewHP': 20, 'HP': 20, 'NewX': 7, 'NewY': 14, 'Crit': True, 'Miss': False, 'ID': 514, 'Unit': <Unit: Unit object>}}
[06/09/17 08:44:32 PM  router.py:247] DEBUG Response: {'Request_ID': u'6', 'Unit': {'NewHP': 20, 'HP': 20, 'NewX': 7, 'NewY': 14, 'Crit': True, 'Miss': False, 'ID': 514}, 'Success': True, 'Target': {'NewHP': 8, 'HP': 15, 'Counter': True, 'Crit': False, 'Miss': True, 'ID': 524}}
[06/09/17 08:44:32 PM testhelper:185] DEBUG ============ Finishing Test: test_ta_12_crit_attack_success ============
```

**Comment by DaBernMon** [comment]
Will be resolved when PR #193 is merged.
